### ISSUE TITLE
Compile fatal error after composer change

### ISSUE THREAD

**Issue by JoryHogeveen** [SendCloud/sendcloud#138] opened 2022-09-02 11:55 UTC
```
Compilation was started.
Repositories code generation... 1/8 [===>------------------------]  12% 1 sec 48.0 MiBPHP Fatal error:  Uncaught Error: Class 'Magento\Multishipping\Block\Checkout\Overview' not found in /data/web/magento2/vendor/sendcloud/sendcloud/Block/Checkout/Overview.php:9
Stack trace:
#0 /data/web/magento2/vendor/composer/ClassLoader.php(444): include()
#1 /data/web/magento2/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/data/web/magen...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('SendCloud\\SendC...')
#3 [internal function]: spl_autoload_call('SendCloud\\SendC...')
#4 /data/web/magento2/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(134): class_exists('SendCloud\\SendC...')
#5 /data/web/magento2/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(117): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClass('SendCloud\\SendC...', '/data/web/magen...')
#6 /data/web/magento2/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(87): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->extract(Object(RecursiveIteratorIterator) in /data/web/magento2/vendor/sendcloud/sendcloud/Block/Checkout/Overview.php on line 9
```

**Comment by teodoratimoti** [comment] 2022-09-21 09:34
JoryHogeveen,

Thank you for reaching out. This is just a quick note to inform you that we received your ticket.

Our team will take this issue into consideration as soon as possible.
We will keep you updated.

Best regards.

**Comment by JoryHogeveen** [comment] 2022-09-21 09:38
Hi @teodoratimoti 

Sorry for the silence here. Hold on just yet on putting your dev team on this.
I got a notice from the original shop dev that this might be a third party plugins issue!

**Comment by teodoratimoti** [comment] 2022-09-22 07:52
Hi @JoryHogeveen,

Thank you for this information.
Can you please just notify us when you make sure that this is a third-party plugin issue?

Thank you,

Best regards.

**Comment by logeecom** [comment] 2022-10-04 07:50
Hi @JoryHogeveen,

We will close this issue since there are no additional inputs that the issue is related to the Sendcloud plugin.

If you experience the same issue, please forward your request via the Support page in sendcloud: https://app.sendcloud.com/v2/support or reach out to support@sendcloud.com.

If possible please describe clearly the issue and add examples where possible.

I hope I have informed you sufficiently and wish you a great day!

**Closed** 2022-10-04 07:50 UTC
